config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'web/index'
  get 'web/about'
  get 'web/contact'
  resources :sliders
  resources :tags
  resources :categories
  resources :products
  namespace :admin do
    devise_for :users  
    resources :users, only: [:index]
      
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "up" => "rails/health#show", as: :rails_health_check
  root "web#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <ul class="nav-list">
    <li class="nav-item"><%= link_to "Home", web_index_path %></li>
    <li class="nav-item"><%= link_to "About", web_about_path %></li>
    <li class="nav-item"><%= link_to "Contact", web_contact_path %></li>
    <li class="nav-item"><%= link_to "Users", users_index_path %></li>
    <li class="nav-item"><%= link_to "Products", products_path %></li>
    <li class="nav-item"><%= link_to "Categories", categories_path %></li>
    <li class="nav-item"><%= link_to "Tags", tags_path %></li>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<nav class="sidebar">
  <ul class="sidebar-list">
    <li class="nav-item"><%= link_to "Home", web_index_path %></li>
    <li class="nav-item"><%= link_to "About", web_about_path %></li>
    <li class="nav-item"><%= link_to "Contact", web_contact_path %></li>
    <li class="nav-item"><%= link_to "Users", users_index_path %></li>
    <li class="nav-item"><%= link_to "Products", products_path %></li>
    <li class="nav-item"><%= link_to "Categories", categories_path %></li>
    <li class="nav-item"><%= link_to "Tags", tags_path %></li>
  </ul>
</nav>